services:
  db:
    image: postgres:18-alpine
    container_name: postgres18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

